import{renderEmbed}from './embeds.js';import{escapeHtml}from './config.js';import{focusCamera,pauseGlobeRotation,resumeGlobeRotation}from './globe.js';const drawer=document.getElementById('pinDrawer');const scrim=document.getElementById('scrim');const drawerEmbed=document.getElementById('drawerEmbed');let isDrawerOpen=!1;let openedAt=0;const GHOST_CLICK_GUARD_MS=400;export function initDrawer(){document.getElementById('drawerClose').addEventListener('click',closeDrawer);scrim.addEventListener('click',()=>{if(Date.now()-openedAt<GHOST_CLICK_GUARD_MS)return;closeDrawer()})}
export function openDrawerForRegion(regionName,sightingsList,centroid){const count=sightingsList.length;document.getElementById('drawerCat').textContent=`${count} post${count === 1 ? '' : 's'}`;document.getElementById('drawerTitle').textContent=regionName;document.getElementById('drawerCoords').textContent=count?'Scroll to browse every sighting in this area':'No sightings match the current filter here';drawerEmbed.innerHTML='';drawerEmbed.classList.add('drawer__feed');if(!count){const empty=document.createElement('div');empty.className='embed-fallback';empty.textContent='Nothing pinned here yet for this month/year — try widening the date filter.';drawerEmbed.appendChild(empty)}else{sightingsList.forEach(pin=>drawerEmbed.appendChild(buildFeedCard(pin)))}
if(!isDrawerOpen){pauseGlobeRotation();isDrawerOpen=!0}
openedAt=Date.now();if(centroid){focusCamera(centroid.lat,centroid.lng,1.5,1000)}
drawer.classList.add('is-open');drawer.setAttribute('aria-hidden','false');scrim.classList.add('is-visible')}
function buildFeedCard(pin){const card=document.createElement('div');card.className='drawer__feed-card';const head=document.createElement('div');head.className='drawer__feed-head';head.innerHTML=`
    <span class="drawer__cat">${escapeHtml(pin.category)}</span>
    <span class="drawer__feed-title">${escapeHtml(pin.title)}</span>
  `;card.appendChild(head);const embedWrap=document.createElement('div');embedWrap.className='drawer__feed-embed';renderEmbed(pin,embedWrap);card.appendChild(embedWrap);const link=document.createElement('a');link.className='drawer__link';link.href=pin.social_url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Open original post ↗';card.appendChild(link);const credit=buildCreditEl(pin);if(credit)card.appendChild(credit);return card}
function buildCreditEl(pin){if(!pin.submitterName)return null;const el=document.createElement(pin.submitterProfileUrl?'a':'span');el.className='drawer__credit';el.textContent=`Added by ${pin.submitterName}`;if(pin.submitterProfileUrl){el.href=pin.submitterProfileUrl;el.target='_blank';el.rel='noopener noreferrer'}
return el}
export function closeDrawer(){drawer.classList.remove('is-open');drawer.setAttribute('aria-hidden','true');scrim.classList.remove('is-visible');if(isDrawerOpen){resumeGlobeRotation();isDrawerOpen=!1}}
