import{categoryColor,escapeHtml,rgbaFromHex}from './config.js';import{feature as topojsonFeature}from 'https://unpkg.com/topojson-client@3?module';const COUNTRIES_GEOJSON_URL='https://raw.githubusercontent.com/vasturiano/globe.gl/master/example/datasets/ne_110m_admin_0_countries.geojson';const US_STATES_TOPOJSON_URL='https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json';const OCEAN_COLOR='#35A7FF';const LAND_COLOR='#FFE5D9';const LAND_HOVER_COLOR='#FFE94A';const LAND_SCHEDULE_COLOR='#38B000';const OUTLINE_COLOR='#0f172a';const LAND_ALTITUDE=0.008;const LAND_HOVER_ALTITUDE=0.02;const LAND_SCHEDULE_ALTITUDE=0.014;const POINT_ALTITUDE=0.026;const PULSE_ALTITUDE=0.028;const JITTER_THRESHOLD_DEG=0.0005;const JITTER_RADIUS_DEG=0.002;const ARC_COLOR_HIGHLIGHT='rgba(56,176,0,0.95)';const ARC_COLOR_FUTURE_START='rgba(255,89,100,0.4)';const ARC_COLOR_FUTURE_END='rgba(157,107,255,0.4)';const ARC_COLOR_PAST='rgba(255,140,26,0.85)';const ARC_ALTITUDE_SCALE=0.5;const STATUS_REFRESH_INTERVAL_MS=60_000;const ARC_DASH_LENGTH=0.4;const ARC_DASH_GAP=4;const ARC_DASH_ANIMATE_MS=2500;const BROKEN_DASH_LENGTH=0.12;const BROKEN_DASH_GAP=0.12;const BROKEN_DASH_ANIMATE_MS=6000;function arcDashLengthFor(status){return status==='future'?ARC_DASH_LENGTH:BROKEN_DASH_LENGTH}
function arcDashGapFor(status){return status==='future'?ARC_DASH_GAP:BROKEN_DASH_GAP}
function arcDashAnimateTimeFor(status){return status==='future'?ARC_DASH_ANIMATE_MS:BROKEN_DASH_ANIMATE_MS}
const USER_ROTATE_PAUSE_MS=3000;const IS_MOBILE=window.matchMedia('(pointer: coarse)').matches||window.innerWidth<=768;const AUTO_ROTATE_SPEED=IS_MOBILE?0.15:0.35;const MAX_PIXEL_RATIO=IS_MOBILE?1.5:2;const POINT_RESOLUTION=12;const RING_MAX_RADIUS_DEG=3;const RING_PROPAGATION_SPEED_DEG_PER_SEC=1.2;const RING_REPEAT_PERIOD_BASE_MS=1400;const RING_REPEAT_PERIOD_JITTER_MS=900;const MONTH_NAMES=['January','February','March','April','May','June','July','August','September','October','November','December'];let world=null;let hoveredPolygon=null;let masterSightings=[];let hiddenCategories=[];let dateFilter={month:'all',year:'all'};let regionClickHandler=null;let rotationLockCount=0;let userRotateResumeTimeout=null;let flightTrajectories=[];let statusRefreshHandle=null;let scheduleHighlightPolygon=null;export function buildGlobe(sightings,{onRegionClick,onGlobeClick}){const el=document.getElementById('globeViz');masterSightings=sightings;regionClickHandler=onRegionClick;world=Globe()(el).globeImageUrl(null).backgroundColor('rgba(0,0,0,0)').showAtmosphere(!0).atmosphereColor(OCEAN_COLOR).atmosphereAltitude(0.18).width(window.innerWidth).height(window.innerHeight).polygonsData([]).polygonCapColor(d=>polygonCapColorFor(d)).polygonSideColor(()=>'rgba(15,23,42,0.55)').polygonStrokeColor(()=>OUTLINE_COLOR).polygonAltitude(d=>polygonAltitudeFor(d)).polygonsTransitionDuration(150).polygonLabel(d=>`
      <div class="cartoon-tooltip">
        <strong>${escapeHtml(d.properties?.displayName || 'Unknown')}</strong>
      </div>
    `).onPolygonHover(d=>{hoveredPolygon=d;world.polygonCapColor(p=>polygonCapColorFor(p)).polygonAltitude(p=>polygonAltitudeFor(p));el.style.cursor=d?'pointer':'grab'}).onPolygonClick(handlePolygonClick).pointsData([]).pointLat('displayLat').pointLng('displayLng').pointColor(d=>categoryColor(d.category)).pointAltitude(POINT_ALTITUDE).pointRadius(0.36).pointResolution(POINT_RESOLUTION).pointLabel(d=>`
      <div class="cartoon-tooltip">
        <strong>${escapeHtml(d.title)}</strong><br/>${escapeHtml(d.category)}
      </div>
    `).arcsData([]).arcColor(d=>statusArcColor(d._status)).arcAltitudeAutoScale(ARC_ALTITUDE_SCALE).arcStroke(d=>(d._status==='current'?1:0.45)).arcDashLength(d=>arcDashLengthFor(d._status)).arcDashGap(d=>arcDashGapFor(d._status)).arcDashInitialGap(d=>arcDashJitterFraction(d)*(arcDashLengthFor(d._status)+arcDashGapFor(d._status))).arcDashAnimateTime(d=>arcDashAnimateTimeFor(d._status)).arcLabel(d=>`
      <div class="cartoon-tooltip">
        <strong>${escapeHtml(d.startPlace)} → ${escapeHtml(d.endPlace)}</strong><br/>
        ${formatArcDate(d.departureTime)} → ${formatArcDate(d.arrivalTime)}
      </div>
    `).ringsData([]).ringLat('displayLat').ringLng('displayLng').ringAltitude(PULSE_ALTITUDE).ringColor(d=>ringColorFor(d)).ringMaxRadius(RING_MAX_RADIUS_DEG).ringPropagationSpeed(RING_PROPAGATION_SPEED_DEG_PER_SEC).ringRepeatPeriod(d=>RING_REPEAT_PERIOD_BASE_MS+ringJitterFraction(d)*RING_REPEAT_PERIOD_JITTER_MS).onGlobeClick(onGlobeClick);const mat=world.globeMaterial();mat.color.set(OCEAN_COLOR);mat.shininess=0;world.renderer().setPixelRatio(Math.min(window.devicePixelRatio||1,MAX_PIXEL_RATIO));world.controls().autoRotate=!0;world.controls().autoRotateSpeed=AUTO_ROTATE_SPEED;world.controls().enableDamping=!0;world.controls().addEventListener('start',()=>{clearTimeout(userRotateResumeTimeout);world.controls().autoRotate=!1});world.controls().addEventListener('end',()=>{clearTimeout(userRotateResumeTimeout);userRotateResumeTimeout=setTimeout(()=>{if(rotationLockCount===0)world.controls().autoRotate=!0},USER_ROTATE_PAUSE_MS)});window.addEventListener('resize',()=>{world.width(window.innerWidth).height(window.innerHeight)});loadPolygonData().then(features=>{world.polygonsData(features);refreshTrajectoryDisplay()}).catch(err=>console.error('Failed to load country/state polygons:',err));initDateFilter(sightings);redrawDots();return world}
function ringColorFor(d){const hex=categoryColor(d.category);return t=>rgbaFromHex(hex,1-t)}
function ringJitterFraction(d){return stableHashFraction(d.social_url||d.title||'')}
function arcDashJitterFraction(t){return stableHashFraction(`${t.startPlace}|${t.endPlace}|${t.departureTime}`)}
function stableHashFraction(str){let hash=0;for(let i=0;i<str.length;i++){hash=(hash<<5)-hash+str.charCodeAt(i);hash|=0}
return(Math.abs(hash)%1000)/1000}
function polygonCapColorFor(p){if(p===hoveredPolygon)return LAND_HOVER_COLOR;if(p===scheduleHighlightPolygon)return LAND_SCHEDULE_COLOR;return LAND_COLOR}
function polygonAltitudeFor(p){if(p===hoveredPolygon)return LAND_HOVER_ALTITUDE;if(p===scheduleHighlightPolygon)return LAND_SCHEDULE_ALTITUDE;return LAND_ALTITUDE}
function initDateFilter(sightings){const monthSel=document.getElementById('filter-month');const yearSel=document.getElementById('filter-year');if(!monthSel||!yearSel)return;monthSel.innerHTML='<option value="all">All Months</option>'+MONTH_NAMES.map((name,i)=>`<option value="${i + 1}">${name}</option>`).join('');const years=[...new Set(sightings.map(s=>(s.date||'').slice(0,4)).filter(Boolean))].sort();yearSel.innerHTML='<option value="all">All Years</option>'+years.map(y=>`<option value="${y}">${y}</option>`).join('');monthSel.addEventListener('change',()=>{dateFilter.month=monthSel.value;redrawDots()});yearSel.addEventListener('change',()=>{dateFilter.year=yearSel.value;redrawDots()})}
function passesDateFilter(sighting){if(dateFilter.month==='all'&&dateFilter.year==='all')return!0;if(!sighting.date)return!1;const[year,month]=sighting.date.split('-');if(dateFilter.year!=='all'&&year!==dateFilter.year)return!1;if(dateFilter.month!=='all'&&String(Number(month))!==dateFilter.month)return!1;return!0}
function getVisibleSightings(){return masterSightings.filter(s=>!hiddenCategories.includes(s.category)).filter(passesDateFilter)}
function redrawDots(){if(!world)return;const visible=getVisibleSightings();const withJitter=applyDisplayJitter(visible);world.pointsData(withJitter).ringsData(withJitter).arcsData(flightTrajectories)}
function applyDisplayJitter(sightings){const groups=new Map();for(const s of sightings){if(s.lat==null||s.lng==null)continue;const key=jitterGroupKey(s.lat,s.lng);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(s)}
const jittered=[];for(const group of groups.values()){if(group.length===1){const s=group[0];jittered.push({...s,_kind:'pulse',realLat:s.lat,realLng:s.lng,displayLat:s.lat,displayLng:s.lng});continue}
const n=group.length;const centerLat=group.reduce((sum,s)=>sum+s.lat,0)/n;const centerLng=group.reduce((sum,s)=>sum+s.lng,0)/n;const lngScale=1/Math.max(0.15,Math.cos((centerLat*Math.PI)/180));group.forEach((s,i)=>{const angle=(2*Math.PI*i)/n;jittered.push({...s,_kind:'pulse',realLat:s.lat,realLng:s.lng,displayLat:centerLat+JITTER_RADIUS_DEG*Math.sin(angle),displayLng:centerLng+JITTER_RADIUS_DEG*lngScale*Math.cos(angle),})})}
return jittered}
function jitterGroupKey(lat,lng){const cell=1/JITTER_THRESHOLD_DEG;return `${Math.round(lat * cell)}:${Math.round(lng * cell)}`}
function handlePolygonClick(polygon){if(!polygon)return;const regionName=polygon.properties?.displayName||'Unknown region';const matches=getVisibleSightings().filter(s=>pointInFeature([s.lng,s.lat],polygon.geometry));const centroid=regionCentroid(polygon.geometry);regionClickHandler?.(regionName,matches,centroid)}
function regionCentroid(geometry){if(!geometry)return null;const candidatePolygons=geometry.type==='Polygon'?[geometry.coordinates]:geometry.type==='MultiPolygon'?geometry.coordinates:null;if(!candidatePolygons||!candidatePolygons.length)return null;let largest=candidatePolygons[0];let largestArea=polygonNetArea(largest);for(let i=1;i<candidatePolygons.length;i++){const area=polygonNetArea(candidatePolygons[i]);if(area>largestArea){largestArea=area;largest=candidatePolygons[i]}}
const pole=poleOfInaccessibility(largest);if(pole)return pole;const ring=largest[0];if(!ring||!ring.length)return null;const sum=ring.reduce((acc,[lng,lat])=>{acc.lat+=lat;acc.lng+=lng;return acc},{lat:0,lng:0});return{lat:sum.lat/ring.length,lng:sum.lng/ring.length}}
function polygonNetArea(rings){let area=Math.abs(ringArea(rings[0]));for(let i=1;i<rings.length;i++){area-=Math.abs(ringArea(rings[i]))}
return area}
function ringArea(ring){let sum=0;for(let i=0,j=ring.length-1;i<ring.length;j=i++){sum+=(ring[j][0]*ring[i][1])-(ring[i][0]*ring[j][1])}
return sum/2}
function poleOfInaccessibility(rings){const outer=rings[0];if(!outer||!outer.length)return null;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const[x,y]of outer){if(x<minX)minX=x;if(x>maxX)maxX=x;if(y<minY)minY=y;if(y>maxY)maxY=y}
const GRID=12;const ITERATIONS=5;let cx=(minX+maxX)/2;let cy=(minY+maxY)/2;let halfW=(maxX-minX)/2;let halfH=(maxY-minY)/2;let best={x:cx,y:cy,d:-Infinity};for(let iter=0;iter<ITERATIONS;iter++){let found={x:cx,y:cy,d:-Infinity};for(let i=0;i<=GRID;i++){const x=cx-halfW+(2*halfW*i)/GRID;for(let j=0;j<=GRID;j++){const y=cy-halfH+(2*halfH*j)/GRID;const d=signedDistanceToRings([x,y],rings);if(d>found.d)found={x,y,d}}}
if(found.d>best.d)best=found;cx=found.x;cy=found.y;halfW/=GRID/2;halfH/=GRID/2}
return best.d>0?{lat:best.y,lng:best.x}:null}
function signedDistanceToRings(point,rings){const inside=pointInPolygonCoords(point,rings);let minDist=Infinity;for(const ring of rings){for(let i=0,len=ring.length,j=len-1;i<len;j=i++){const d=distToSegment(point,ring[j],ring[i]);if(d<minDist)minDist=d}}
return inside?minDist:-minDist}
function distToSegment([px,py],[ax,ay],[bx,by]){const dx=bx-ax;const dy=by-ay;const lenSq=dx*dx+dy*dy;let t=lenSq===0?0:((px-ax)*dx+(py-ay)*dy)/lenSq;t=Math.max(0,Math.min(1,t));const nx=ax+t*dx;const ny=ay+t*dy;return Math.hypot(px-nx,py-ny)}
const COASTAL_TOLERANCE_KM=2;function pointInFeature(point,geometry,toleranceKm=COASTAL_TOLERANCE_KM){if(!geometry)return!1;const exactMatch=geometry.type==='Polygon'?pointInPolygonCoords(point,geometry.coordinates):geometry.type==='MultiPolygon'?geometry.coordinates.some(poly=>pointInPolygonCoords(point,poly)):!1;if(exactMatch||toleranceKm<=0)return exactMatch;return distanceToGeometryKm(point,geometry)<=toleranceKm}
function pointInPolygonCoords(point,rings){let inside=!1;for(const ring of rings){if(rayCast(point,ring))inside=!inside}
return inside}
function rayCast([x,y],ring){let inside=!1;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const[xi,yi]=ring[i];const[xj,yj]=ring[j];const intersect=(yi>y)!==(yj>y)&&x<((xj-xi)*(y-yi))/(yj-yi)+xi;if(intersect)inside=!inside}
return inside}
function distanceToGeometryKm(point,geometry){const polygons=geometry.type==='Polygon'?[geometry.coordinates]:geometry.type==='MultiPolygon'?geometry.coordinates:[];const[px,py]=point;const kmPerDegLng=111.320*Math.cos((py*Math.PI)/180);const kmPerDegLat=110.574;let minDistKm=Infinity;for(const rings of polygons){for(const ring of rings){for(let i=0,len=ring.length,j=len-1;i<len;j=i++){const a=[(ring[j][0]-px)*kmPerDegLng,(ring[j][1]-py)*kmPerDegLat];const b=[(ring[i][0]-px)*kmPerDegLng,(ring[i][1]-py)*kmPerDegLat];const d=distToSegment([0,0],a,b);if(d<minDistKm)minDistKm=d}}}
return minDistKm}
async function loadPolygonData(){const[countriesGeo,statesTopo]=await Promise.all([fetch(COUNTRIES_GEOJSON_URL).then(res=>res.json()),fetch(US_STATES_TOPOJSON_URL).then(res=>res.json()),]);const countryFeatures=countriesGeo.features.filter(f=>!isUnitedStates(f)).map(f=>{f.properties.displayName=f.properties?.NAME||f.properties?.name||'Unknown';return f});const stateFeatures=topojsonFeature(statesTopo,statesTopo.objects.states).features.map(f=>{const stateName=f.properties?.name||'Unknown';f.properties.displayName=`${stateName}, United States`;return f});return[...countryFeatures,...stateFeatures]}
function isUnitedStates(feature){const p=feature.properties||{};return(p.ISO_A3==='USA'||p.ADM0_A3==='USA'||p.NAME==='United States of America'||p.name==='United States of America')}
export function focusCamera(lat,lng,altitude=1.5,duration=1000){if(!world||lat==null||lng==null)return;world.pointOfView({lat,lng,altitude},duration)}
export function pauseGlobeRotation(){rotationLockCount++;if(world)world.controls().autoRotate=!1}
export function resumeGlobeRotation(){rotationLockCount=Math.max(0,rotationLockCount-1);if(world&&rotationLockCount===0)world.controls().autoRotate=!0}
function formatArcDate(isoString){const d=new Date(isoString);if(isNaN(d.getTime()))return'';return `${MONTH_NAMES[d.getMonth()].slice(0, 3)} ${d.getDate()}`}
function statusArcColor(status){if(status==='past')return[ARC_COLOR_PAST,ARC_COLOR_PAST];if(status==='current')return[ARC_COLOR_HIGHLIGHT,ARC_COLOR_HIGHLIGHT];return[ARC_COLOR_FUTURE_START,ARC_COLOR_FUTURE_END]}
function annotateTrajectoryStatuses(trajectories){const now=Date.now();let highlightAssigned=!1;return trajectories.map(t=>{const arrived=new Date(t.arrivalTime).getTime()<now;if(arrived)return{...t,_status:'past'};if(!highlightAssigned){highlightAssigned=!0;return{...t,_status:'current'}}
return{...t,_status:'future'}})}
function findScheduleHighlightPolygon(annotated){if(!world)return null;const current=annotated.find(t=>t._status==='current');const target=current||annotated[annotated.length-1];if(!target)return null;const polygons=world.polygonsData();return polygons.find(p=>pointInFeature([target.endLng,target.endLat],p.geometry))||null}
function refreshTrajectoryDisplay(){if(!world)return;const annotated=annotateTrajectoryStatuses(flightTrajectories);scheduleHighlightPolygon=findScheduleHighlightPolygon(annotated);world.arcsData(annotated).polygonCapColor(p=>polygonCapColorFor(p)).polygonAltitude(p=>polygonAltitudeFor(p))}
export function setTrajectories(trajectories){flightTrajectories=trajectories||[];refreshTrajectoryDisplay();if(!statusRefreshHandle){statusRefreshHandle=setInterval(refreshTrajectoryDisplay,STATUS_REFRESH_INTERVAL_MS)}}
export function getWorld(){return world}
export function refreshGlobeData(sightings){masterSightings=sightings;redrawDots()}
export function filterGlobeData(sightings,hidden){masterSightings=sightings;hiddenCategories=hidden;redrawDots()}
